# Generated by Django 5.1.5 on 2025-01-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='charts.metrictype')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='charts_time_timesta_ab2769_idx'), models.Index(fields=['metric_type', 'timestamp'], name='charts_time_metric__d7c226_idx')],
            },
        ),
    ]
