# Generated by Django 5.1.5 on 2025-01-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseriesmetric',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
