# Generated by Django 5.1.5 on 2025-01-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_timeseriesmetric_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictype',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
